FROM golang:1.24-alpine AS build

WORKDIR /go/src/app

COPY . .
# RUN go mod download && go mod verify

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /go/src/app/apps/market-simulator
RUN export flags="-s -w" && \
    go build -ldflags "${flags}" -o /go/bin/app .

FROM alpine

RUN apk add --no-cache bash

WORKDIR /app

COPY --from=build /go/bin/ ./
COPY --from=build /go/src/app/apps/wait-for-it.sh ./
RUN chmod +x ./wait-for-it.sh

CMD ["./app"]
