FROM node:18-alpine as base

EXPOSE 3000

RUN apk update && apk add --no-cache git openssh ca-certificates
WORKDIR /app
RUN npm install -g vite && npm install -g tsc

COPY . .

RUN npm install && npm run build && \
rm -rf node_modules

FROM nginx:1.23.3-alpine

RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
RUN mkdir -p /usr/share/nginx/html
COPY --from=base /app/dist /usr/share/nginx/html
EXPOSE 80
ADD ./prepare.sh ./
RUN chmod +x ./prepare.sh
CMD ["./prepare.sh"]
