// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: domain/state/state.proto

package state

import (
	metadata "github.com/CoreumFoundation/CoreDEX-API/domain/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateType int32

const (
	StateType_NOT_USED     StateType = 0
	StateType_BLOCK_HEIGHT StateType = 1
)

// Enum value maps for StateType.
var (
	StateType_name = map[int32]string{
		0: "NOT_USED",
		1: "BLOCK_HEIGHT",
	}
	StateType_value = map[string]int32{
		"NOT_USED":     0,
		"BLOCK_HEIGHT": 1,
	}
)

func (x StateType) Enum() *StateType {
	p := new(StateType)
	*p = x
	return p
}

func (x StateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_state_state_proto_enumTypes[0].Descriptor()
}

func (StateType) Type() protoreflect.EnumType {
	return &file_domain_state_state_proto_enumTypes[0]
}

func (x StateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateType.Descriptor instead.
func (StateType) EnumDescriptor() ([]byte, []int) {
	return file_domain_state_state_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateType StateType          `protobuf:"varint,1,opt,name=StateType,proto3,enum=state.StateType" json:"StateType,omitempty"`
	Content   string             `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	MetaData  *metadata.MetaData `protobuf:"bytes,3,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_state_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_domain_state_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_domain_state_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetStateType() StateType {
	if x != nil {
		return x.StateType
	}
	return StateType_NOT_USED
}

func (x *State) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *State) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

var File_domain_state_state_proto protoreflect.FileDescriptor

var file_domain_state_state_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x1a, 0x1e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x81, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x2b, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x48, 0x45, 0x49, 0x47, 0x48, 0x54,
	0x10, 0x01, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x6f, 0x72, 0x62, 0x65, 0x72, 0x74, 0x76, 0x61, 0x6e, 0x6e, 0x6f, 0x62, 0x65, 0x6c,
	0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x75, 0x6d, 0x2d, 0x64, 0x65, 0x78, 0x2d, 0x61, 0x70,
	0x69, 0x2d, 0x76, 0x32, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_state_state_proto_rawDescOnce sync.Once
	file_domain_state_state_proto_rawDescData = file_domain_state_state_proto_rawDesc
)

func file_domain_state_state_proto_rawDescGZIP() []byte {
	file_domain_state_state_proto_rawDescOnce.Do(func() {
		file_domain_state_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_state_state_proto_rawDescData)
	})
	return file_domain_state_state_proto_rawDescData
}

var file_domain_state_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_state_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_state_state_proto_goTypes = []interface{}{
	(StateType)(0),            // 0: state.StateType
	(*State)(nil),             // 1: state.State
	(*metadata.MetaData)(nil), // 2: metadata.MetaData
}
var file_domain_state_state_proto_depIdxs = []int32{
	0, // 0: state.State.StateType:type_name -> state.StateType
	2, // 1: state.State.MetaData:type_name -> metadata.MetaData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_state_state_proto_init() }
func file_domain_state_state_proto_init() {
	if File_domain_state_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_state_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_state_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_state_state_proto_goTypes,
		DependencyIndexes: file_domain_state_state_proto_depIdxs,
		EnumInfos:         file_domain_state_state_proto_enumTypes,
		MessageInfos:      file_domain_state_state_proto_msgTypes,
	}.Build()
	File_domain_state_state_proto = out.File
	file_domain_state_state_proto_rawDesc = nil
	file_domain_state_state_proto_goTypes = nil
	file_domain_state_state_proto_depIdxs = nil
}
