// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: domain/order-properties/order-properties.proto

package orderproperties

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side is order side.
type Side int32

const (
	// SIDE_UNSPECIFIED reserves the default value, to protect against unexpected settings.
	Side_SIDE_UNSPECIFIED Side = 0
	// SIDE_BUY means that the order is to buy base_denom quantity with the price.
	Side_SIDE_BUY Side = 1
	// SIDE_SELL means that the order is to sell base_denom quantity with the price.
	Side_SIDE_SELL Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_order_properties_order_properties_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_domain_order_properties_order_properties_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_domain_order_properties_order_properties_proto_rawDescGZIP(), []int{0}
}

var File_domain_order_properties_order_properties_proto protoreflect.FileDescriptor

var file_domain_order_properties_order_properties_proto_rawDesc = string([]byte{
	0x0a, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x2a, 0x39, 0x0a, 0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x49, 0x44,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x42, 0x55, 0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x42, 0x51, 0x5a, 0x4f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x72, 0x65, 0x75,
	0x6d, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x43, 0x6f, 0x72, 0x65,
	0x44, 0x45, 0x58, 0x2d, 0x41, 0x50, 0x49, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x3b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_domain_order_properties_order_properties_proto_rawDescOnce sync.Once
	file_domain_order_properties_order_properties_proto_rawDescData []byte
)

func file_domain_order_properties_order_properties_proto_rawDescGZIP() []byte {
	file_domain_order_properties_order_properties_proto_rawDescOnce.Do(func() {
		file_domain_order_properties_order_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_order_properties_order_properties_proto_rawDesc), len(file_domain_order_properties_order_properties_proto_rawDesc)))
	})
	return file_domain_order_properties_order_properties_proto_rawDescData
}

var file_domain_order_properties_order_properties_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_order_properties_order_properties_proto_goTypes = []any{
	(Side)(0), // 0: orderproperties.Side
}
var file_domain_order_properties_order_properties_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_order_properties_order_properties_proto_init() }
func file_domain_order_properties_order_properties_proto_init() {
	if File_domain_order_properties_order_properties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_order_properties_order_properties_proto_rawDesc), len(file_domain_order_properties_order_properties_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_order_properties_order_properties_proto_goTypes,
		DependencyIndexes: file_domain_order_properties_order_properties_proto_depIdxs,
		EnumInfos:         file_domain_order_properties_order_properties_proto_enumTypes,
	}.Build()
	File_domain_order_properties_order_properties_proto = out.File
	file_domain_order_properties_order_properties_proto_goTypes = nil
	file_domain_order_properties_order_properties_proto_depIdxs = nil
}
