name: Build and Push to DockerHub

on:
  push:
    branches:
      - main

env:
  ORG: coreumfoundation

jobs:
  setup-build-publish-webhook:
    strategy:
        fail-fast: false
        matrix:
          applications: [
            "api-server",
            "data-aggregator",
            "frontend",
            "store",
          ]
          include:
            - application: "lint"
            - application: "data-aggregator"
            - application: "frontend"
            - application: "store"


    name: Setup, Build, Publish, Webhook
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        # if git tag is present, set it to BDJUNO_FULL_TAG_NAME and HASURA_FULL_TAG_NAME, else put empty string
        run: |
          echo "SHA8=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push app
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.${{ matrix.ci_step }}
          context: .
          push: true
          # if tag is an empty string, plugin will skip that tag.
          tags: |
            ${{ env.ORG }}/${{ matrix.ci_step }}:latest
            ${{ env.ORG }}/${{ matrix.ci_step }}:${{ env.SHA8 }}
